/* AUTO-GENERATED by build_knowledge.mjs — the mind of Maison J·H.
   Company work carries a synopsis and a company tag only; never source code. */
window.KNOWLEDGE = {
  "generated": "2026-07-09",
  "subject": "Jazmia Henry — Principal Research Engineer",
  "profile": {
    "name": "Jazmia Henry",
    "title": "Principal Research Engineer",
    "yearsExperience": 15,
    "contact": {
      "email": "jazmia.henry@gmail.com",
      "github": "github.com/jazmiahenry",
      "linkedin": "linkedin.com/in/jazmiahenry",
      "site": "jazmiahenry.com",
      "scholar": "Google Scholar"
    },
    "summary": "Principal Research Engineer and AI leader with 15+ years building and shipping production AI systems — from Morgan Stanley to Head of ML at The Motley Fool to Microsoft Research, and founder of Iso AI. Deep, hands-on expertise across reinforcement learning, foundation models, evaluation and efficient inference, with a track record of building teams and delivering measurable business impact.",
    "leadership": [
      "Built and led ML organizations (0 → 7 engineers at The Motley Fool); founder & CAO of Iso AI.",
      "$40M revenue impact and $400M valuation lift; 95% churn reduction; 80% training-time reduction on a distributed RL platform at Microsoft.",
      "One USPTO-published patent, NeurIPS keynote & area chair, six NeurIPS reviews, published author (McGraw-Hill, Bloomsbury)."
    ]
  },
  "education": [
    {
      "school": "University of Oxford",
      "detail": "DPhil (ABD) · St. Hilda’s College",
      "note": "AI / Information"
    },
    {
      "school": "Stanford University",
      "detail": "HAI & PACS — Research affiliation"
    },
    {
      "school": "Columbia University",
      "detail": "Graduate study"
    },
    {
      "school": "Tulane University",
      "detail": "Undergraduate"
    }
  ],
  "topicExperience": {
    "LLMs / Foundation Models": {
      "since": 2023,
      "years": 3
    },
    "Systems / Distributed Training": {
      "since": 2020,
      "years": 6
    },
    "Reinforcement Learning": {
      "since": 2022,
      "years": 4
    },
    "Embeddings & Retrieval": {
      "since": 2023,
      "years": 3
    },
    "Simulation": {
      "since": 2018,
      "years": 8
    },
    "Evaluation": {
      "since": 2022,
      "years": 4
    },
    "Data & Datasets": {
      "since": 2018,
      "years": 8
    },
    "Multi-Agent Systems": {
      "since": 2024,
      "years": 2
    },
    "AI Fairness & Ethics": {
      "since": 2022,
      "years": 4
    },
    "NLP": {
      "since": 2022,
      "years": 4
    },
    "Computer Vision": {
      "since": 2024,
      "years": 2
    },
    "Efficient Inference / Quantization": {
      "since": 2023,
      "years": 3
    }
  },
  "levelRubric": {
    "basis": "Depth of the work itself — the novelty, difficulty, scale and rigor of the artifact, not seniority.",
    "Expert": "Original contribution or frontier-scale: a novel method or from-scratch implementation, a flagship production system at scale, peer-reviewed or patented research, or doctoral research.",
    "Advanced": "Substantial, correct, non-trivial engineering or research built on established methods; production- or research-grade, but not a new method.",
    "Intermediate": "Educational, companion, utility, or exploratory work; correct and useful but limited in novelty or scope."
  },
  "topicOrder": [
    "Reinforcement Learning",
    "LLMs / Foundation Models",
    "Evaluation",
    "AI Fairness & Ethics",
    "Multi-Agent Systems",
    "Simulation",
    "Embeddings & Retrieval",
    "Efficient Inference / Quantization",
    "Systems / Distributed Training",
    "Data & Datasets",
    "NLP",
    "Computer Vision"
  ],
  "nodes": [
    {
      "id": "role-collide",
      "kind": "work",
      "kindLabel": "Role · Principal MTS, AI/ML",
      "label": "RIGGs · Collide",
      "level": "Expert",
      "year": "2025 – present",
      "org": "Collide",
      "is_company_ip": true,
      "topics": [
        "LLMs / Foundation Models",
        "Systems / Distributed Training",
        "Reinforcement Learning",
        "Embeddings & Retrieval"
      ],
      "tags": [
        "mixture-of-experts",
        "petroleum",
        "oil-and-gas",
        "foundation-model",
        "reward-system",
        "moe",
        "sparse-routing",
        "domain-llm",
        "reinforcement-learning",
        "multimodal-embeddings",
        "sub-100ms",
        "nemo",
        "megatron",
        "deepspeed",
        "energy"
      ],
      "tech_stack": [
        "NeMo",
        "Megatron-Core",
        "DeepSpeed ZeRO-3",
        "FSDP2",
        "vLLM",
        "SGLang",
        "Neo4j",
        "Qdrant",
        "LangGraph",
        "Blackwell"
      ],
      "rl_techniques": [
        "16-dimensional reward system",
        "RL for retrieval/routing/calculation"
      ],
      "summary": "Full ownership of the RIGGs platform — a purpose-built mixture-of-experts LLM for petroleum engineering. miniRIGGs (8B) outperforms GPT-5.1, Claude Sonnet 4.5, and Grok 4 on the SPE petroleum exam at orders of magnitude smaller scale. BigRIGGs (120B MoE, 55B+ token corpus) ships a 16-dimensional reward system, simulation environments for retrieval/routing/calculation/long-context reasoning, a custom multimodal embedding stack, and a 70k-node knowledge graph — sub-100ms at production load via sparse expert routing.",
      "excerpt": {
        "type": "quote",
        "text": "RIGGs scored 67.5% on a 40-question subset of the SPE petroleum engineering exam in 15 minutes — outperforming Grok 4 (62.5%, 2 hours), Claude Sonnet 4.5 (52.5%), and GPT 5.1 (4.0%).",
        "source": "SPE Petroleum Engineering Exam benchmark · May 2026",
        "why": "A domain-specialized model beating frontier general models by orders of magnitude less compute — the core thesis of purpose-built foundation models."
      },
      "proof": [
        {
          "label": "EnergyCapital HTX — Houston AI platform reshaping oil & gas",
          "url": "https://energycapitalhtx.com/collide-riggs-ai-platform"
        },
        {
          "label": "Super Data Science ep. 995 — End-to-End Foundation Models for Energy",
          "url": "https://www.superdatascience.com/995"
        },
        {
          "label": "Why We Built RIGGs — a purpose-built LLM for oil & gas",
          "url": "https://www.linkedin.com/pulse/why-we-built-riggs-purpose-built-llm-oil-gas-fracslap--na7tc/"
        },
        {
          "label": "Collide — Petroleum Embeddings for oil & gas retrieval",
          "url": "https://collide.io/resources/petroleum-embeddings-oil-gas-retrieval"
        }
      ],
      "title": "Principal Member of Technical Staff, AI/ML",
      "start": 2025,
      "evidence": [
        "Own the RIGGs platform end-to-end: a 120B-parameter mixture-of-experts LLM for petroleum engineering trained on an on-prem NVIDIA Blackwell cluster.",
        "Shipped miniRIGGs (8B), which beats GPT-5.1, Claude Sonnet 4.5 and Grok 4 on the SPE petroleum engineering exam at orders of magnitude smaller scale.",
        "Designed a 16-dimensional reward system and RL simulation environments for retrieval, routing, calculation and long-context reasoning; sub-100ms inference via sparse expert routing.",
        "Built the full training-to-serving stack — NeMo + Megatron-Core continued pre-training, DeepSpeed ZeRO-3 / FSDP2, a custom multimodal embedding stack and a 70k-node Neo4j knowledge graph, served with vLLM / SGLang."
      ]
    },
    {
      "id": "role-iso",
      "kind": "work",
      "kindLabel": "Founder & Chief AI Officer",
      "label": "Iso AI",
      "level": "Expert",
      "year": "2024",
      "org": "Iso AI",
      "is_company_ip": true,
      "topics": [
        "Simulation",
        "Reinforcement Learning",
        "Evaluation"
      ],
      "tags": [
        "simulation",
        "rl",
        "em-rl",
        "ppo",
        "preference-learning",
        "dpo",
        "evaluation",
        "deterministic-verifier",
        "isopro",
        "isotune",
        "patent",
        "founder",
        "reward-model",
        "self-training"
      ],
      "tech_stack": [
        "Ray",
        "Gymnasium",
        "RLlib",
        "PyTorch"
      ],
      "rl_techniques": [
        "EM-RL",
        "PPO",
        "DPO",
        "EM-MIA-weighted preference re-weighting"
      ],
      "summary": "Founded Iso AI. Built an RL simulation engine running 10K+ concurrent episodes at sub-100ms. IsoTune — EM-RL fine-tuning combining Expectation-Maximization self-training with PPO-driven decision-making and a novel EM-MIA-weighted preference re-weighting. ISOPro — open-source evaluation that replaces learned reward models with deterministic verifiers and runs on a MacBook under 8GB RAM. One USPTO-published patent; NeurIPS 2026 submission under review.",
      "excerpt": {
        "type": "quote",
        "text": "Goodbye prompting and RAGs, hello simulation environments. IsoZero achieves 87% accuracy on the SVAMP test set — zero-shot, with no prompt engineering.",
        "source": "Iso AI · Medium · Aug 2024",
        "why": "The founding thesis: replace brittle prompting/RAG with grounded simulation and deterministic verification."
      },
      "proof": [
        {
          "label": "US Patent US20260080257A1 — simulation platform for LLMs & agents",
          "url": "https://patents.google.com/patent/US20260080257A1/en"
        },
        {
          "label": "Iso AI — Goodbye Prompting and RAGs, Hello Simulation Environments",
          "url": "https://medium.com/@jazmia.henry/iso-ai-goodbye-prompting-and-rags-hello-simulation-environments-105dcd168c33"
        }
      ],
      "title": "Founder & Chief AI Officer",
      "start": 2024,
      "evidence": [
        "Founded Iso AI and authored a USPTO-published patent (US20260080257A1) on a simulation-based platform for developing, testing and deploying LLMs and AI agents.",
        "Built an RL simulation engine running 10K+ concurrent episodes at sub-100ms on Ray, Gymnasium and RLlib.",
        "Created IsoTune (EM-RL fine-tuning combining EM self-training with PPO and EM-MIA-weighted preference re-weighting) and open-source ISOPro, a deterministic-verifier evaluation that runs on a MacBook under 8GB RAM."
      ]
    },
    {
      "id": "role-microsoft",
      "kind": "work",
      "kindLabel": "Lead Applied AI Engineer",
      "label": "Project Bonsai · Microsoft Research",
      "level": "Expert",
      "year": "2022 – 2024",
      "org": "Microsoft Research",
      "is_company_ip": true,
      "topics": [
        "Reinforcement Learning",
        "Systems / Distributed Training",
        "Simulation"
      ],
      "tags": [
        "reinforcement-learning",
        "sac",
        "gail",
        "distributed-training",
        "azure",
        "plato",
        "industrial-rl",
        "manufacturing",
        "finance",
        "production-rl",
        "training-platform"
      ],
      "tech_stack": [
        "SAC",
        "GAIL",
        "Azure",
        "LangChain",
        "LangSmith",
        "Bonsai"
      ],
      "rl_techniques": [
        "SAC",
        "GAIL"
      ],
      "summary": "Co-developed Azure Plato — a distributed training platform and RL package that cut training time 80% through architectural optimization. Built production RL agents for Abbott Nutrition, Shell, PepsiCo, BlackRock, and Moody's; delivered a 27% portfolio-performance improvement on the financial line.",
      "excerpt": {
        "type": "quote",
        "text": "Co-developed Azure Plato, a distributed training platform and RL package that cut training time by 80% through architectural optimization — powering production RL agents for Abbott Nutrition, Shell, PepsiCo, BlackRock and Moody’s.",
        "source": "Microsoft Research · Project Bonsai",
        "why": "Industrial RL in production across manufacturing, energy, CPG and finance — with a platform-level systems win."
      },
      "proof": [],
      "title": "Lead Applied AI Engineer, Microsoft Research",
      "start": 2022,
      "evidence": [
        "Co-developed Azure Plato, a distributed RL training platform and package that cut training time 80% via architectural optimization.",
        "Led delivery of production RL agents (SAC, GAIL) for enterprise customers — Abbott Nutrition, Shell, PepsiCo, BlackRock and Moody’s.",
        "Delivered a 27% portfolio-performance improvement on the financial line and reusable RL tooling across manufacturing, energy, CPG and finance."
      ]
    },
    {
      "id": "role-fool",
      "kind": "work",
      "kindLabel": "Head of Machine Learning",
      "label": "The Motley Fool",
      "level": "Advanced",
      "year": "2020 – 2022",
      "org": "The Motley Fool",
      "is_company_ip": true,
      "topics": [
        "Systems / Distributed Training",
        "Data & Datasets"
      ],
      "tags": [
        "leadership",
        "ml-org",
        "churn",
        "revenue",
        "fintech",
        "production-ml",
        "team-building",
        "recommenders"
      ],
      "tech_stack": [
        "Python",
        "ML platform"
      ],
      "rl_techniques": [],
      "summary": "Built the machine-learning organization from zero to seven engineers. Drove a 95% churn reduction company-wide, $40M in revenue impact, and a $400M valuation lift.",
      "excerpt": {
        "type": "quote",
        "text": "Built the ML organization from zero to seven. 95% churn reduction company-wide. $40M revenue impact. $400M valuation lift.",
        "source": "The Motley Fool · Head of Machine Learning",
        "why": "Leadership plus measurable, board-level business impact from applied ML."
      },
      "proof": [],
      "title": "Head of Machine Learning",
      "start": 2020,
      "evidence": [
        "Founded and led the machine-learning organization, hiring and growing the team from 0 to 7 engineers.",
        "Owned ML strategy and delivery company-wide: drove a 95% churn reduction, $40M revenue impact and a $400M valuation lift.",
        "Stood up the production ML platform and recommendation systems powering member retention and growth."
      ]
    },
    {
      "id": "role-ms",
      "kind": "work",
      "kindLabel": "Senior Data Strategist",
      "label": "Morgan Stanley",
      "level": "Advanced",
      "year": "2018 – 2020",
      "org": "Morgan Stanley",
      "is_company_ip": true,
      "topics": [
        "Simulation",
        "Data & Datasets"
      ],
      "tags": [
        "monte-carlo",
        "simulation",
        "wealth-management",
        "finance",
        "quant",
        "aum",
        "institutional"
      ],
      "tech_stack": [
        "Monte Carlo",
        "Python"
      ],
      "rl_techniques": [],
      "summary": "Built long-horizon Monte Carlo simulations for ultra-high-net-worth wealth-management clients and institutional accounts, spanning $2B+ in assets under management.",
      "excerpt": null,
      "proof": [],
      "title": "Senior Data Strategist",
      "start": 2018,
      "evidence": [
        "Built long-horizon Monte Carlo simulations for ultra-high-net-worth and institutional wealth-management accounts spanning $2B+ in assets under management.",
        "Partnered with advisors and institutional desks to turn quantitative scenario modeling into client-facing strategy."
      ]
    },
    {
      "id": "patent-iso",
      "kind": "patent",
      "kindLabel": "US Patent (pending)",
      "label": "Simulation Platform for LLMs & AI Agents",
      "level": "Expert",
      "year": "2024 · pub. 2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Simulation",
        "Multi-Agent Systems",
        "Evaluation"
      ],
      "tags": [
        "patent",
        "simulation",
        "agents",
        "llm",
        "evaluation",
        "wrapper",
        "state-transition",
        "execution-modes"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "USPTO-published patent US20260080257A1: a simulation-based platform for the development, testing, and deployment of large language models and AI agents. Filed 2024-09-19, published 2026-03-19.",
      "excerpt": {
        "type": "quote",
        "text": "The system includes a simulation environment that manages states and transitions, an AI agent that interacts with this environment, and a wrapper that facilitates data conversion between the two. Modular components decompose the agent’s behavior, while various execution modes optimize their processing.",
        "source": "US20260080257A1 · USPTO",
        "why": "A patented architecture for grounding, testing and deploying agents in simulation — the IP backbone of the Iso line of work."
      },
      "proof": [
        {
          "label": "US20260080257A1 on Google Patents",
          "url": "https://patents.google.com/patent/US20260080257A1/en"
        }
      ],
      "evidence": [
        "Sole inventor on USPTO-published patent US20260080257A1 — a simulation platform for developing, testing and deploying LLMs and AI agents."
      ],
      "start": 2024
    },
    {
      "id": "paper-beyond",
      "kind": "paper",
      "kindLabel": "Paper · NeurIPS 2026 (under review)",
      "label": "Beyond Static Snapshots",
      "level": "Expert",
      "year": "2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Evaluation",
        "LLMs / Foundation Models",
        "Reinforcement Learning"
      ],
      "tags": [
        "evaluation",
        "agentic",
        "reward-hacking",
        "deterministic-verifier",
        "isopro",
        "rlhf",
        "grounded-evaluation",
        "benchmark",
        "neurips"
      ],
      "tech_stack": [],
      "rl_techniques": [
        "RLHF"
      ],
      "summary": "A grounded evaluation framework for language models at the agentic frontier. Argues current LLM evaluation suffers four systematic failures that make reward hacking a predictable consequence of evaluation design, and introduces ISOPro — replacing the learned reward model with a deterministic verifier that eliminates reward hacking by construction in verifiable-reward domains.",
      "excerpt": {
        "type": "quote",
        "text": "These failures compound in RLHF, making reward hacking a predictable consequence of evaluation design. ISOPro replaces the learned reward model with a deterministic verifier, eliminating reward hacking by construction: for verifiable-reward domains, the verifier is the reward signal.",
        "source": "arXiv:2604.17573",
        "why": "Reframes reward hacking as an evaluation-design failure and offers a constructive fix — the deterministic verifier."
      },
      "proof": [
        {
          "label": "arXiv:2604.17573",
          "url": "https://arxiv.org/abs/2604.17573"
        }
      ],
      "evidence": [
        "Authored \"Beyond Static Snapshots\" (NeurIPS 2026, under review): a grounded evaluation framework introducing ISOPro, a deterministic verifier that eliminates reward hacking by construction."
      ],
      "start": 2026
    },
    {
      "id": "paper-scaling",
      "kind": "paper",
      "kindLabel": "Paper · NeurIPS 2023 (Top 5%)",
      "label": "Scaling Laws or the Law of Diminishing Returns",
      "level": "Advanced",
      "year": "2023",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Data & Datasets",
        "LLMs / Foundation Models",
        "Evaluation"
      ],
      "tags": [
        "scaling-laws",
        "data-quality",
        "llm",
        "training-data",
        "neurips",
        "black-in-ai",
        "position-paper"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "A position paper (NeurIPS 2023 Black in AI Workshop, Top 5%) arguing that for very large datasets drawn from low-quality sources, scaling laws break down and the law of diminishing returns takes over. Presents empirical investigations of where scaling works and where it does not, arguing for data quality as a first-class predictor.",
      "excerpt": {
        "type": "quote",
        "text": "In cases of significantly large datasets drawn from low-quality data sources, scaling laws no longer hold true and the law of diminishing returns takes their place.",
        "source": "NeurIPS 2023 · Black in AI Workshop",
        "why": "A contrarian-at-the-time thesis — data quality over raw scale — that has aged extremely well."
      },
      "proof": [
        {
          "label": "Google Scholar — Jazmia Henry",
          "url": "https://scholar.google.com/citations?user=lKGOoGoAAAAJ&hl=en"
        }
      ],
      "evidence": [
        "Authored the Top-5% NeurIPS 2023 paper arguing that scaling low-quality data degrades model performance — data quality over raw scale."
      ],
      "start": 2023
    },
    {
      "id": "paper-prompting-fairness",
      "kind": "paper",
      "kindLabel": "Paper · arXiv",
      "label": "Prompting Fairness: AI as Game Players",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "Evaluation",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "fairness",
        "game-theory",
        "dictator-game",
        "behavioral-economics",
        "llm",
        "evaluation",
        "bias"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Studies fairness and cooperative/competitive behavior in LLMs modeled as game players, probing how framing, trust-conditioning and persona shift a model's fairness decisions in economic games.",
      "excerpt": {
        "type": "quote",
        "text": "Artificial intelligence is becoming a constant in human interaction, and examining how these models portray fairness in game play gives insight into how models make decisions.",
        "source": "arXiv:2402.05786",
        "why": "Turns behavioral game theory into an evaluation instrument for model fairness."
      },
      "proof": [
        {
          "label": "arXiv:2402.05786",
          "url": "https://arxiv.org/abs/2402.05786"
        }
      ],
      "evidence": [
        "Authored \"Prompting Fairness: AI as Game Players\" (arXiv:2402.05786) — a behavioral-economics evaluation of LLM fairness under framing and persona effects."
      ],
      "start": 2024
    },
    {
      "id": "paper-mlops",
      "kind": "paper",
      "kindLabel": "Paper · arXiv",
      "label": "MLOps: A Primer for Policymakers",
      "level": "Intermediate",
      "year": "2023",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Systems / Distributed Training",
        "Data & Datasets"
      ],
      "tags": [
        "mlops",
        "policy",
        "governance",
        "ml-lifecycle",
        "primer"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "A primer framing MLOps for a policy audience — explaining the operational lifecycle of machine learning as an emerging frontier that requires governance attention.",
      "excerpt": null,
      "proof": [
        {
          "label": "arXiv:2301.05775",
          "url": "https://arxiv.org/abs/2301.05775"
        }
      ],
      "evidence": [
        "Co-authored \"MLOps: A Primer for Policymakers\" (arXiv:2301.05775), bridging ML operations and public policy."
      ],
      "start": 2023
    },
    {
      "id": "dataset-aave",
      "kind": "dataset",
      "kindLabel": "Open dataset · Stanford HAI",
      "label": "AAVE Corpora",
      "level": "Expert",
      "year": "2022",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Data & Datasets",
        "AI Fairness & Ethics",
        "NLP"
      ],
      "tags": [
        "dataset",
        "aave",
        "nlp",
        "fairness",
        "representation",
        "dialect",
        "inclusive-nlp",
        "stanford-hai",
        "open-source"
      ],
      "tech_stack": [
        "JSON",
        "Jupyter"
      ],
      "rl_techniques": [],
      "summary": "An open-source corpus of 141,000+ African American Vernacular English words across four collections (lyrics, leadership speeches, book archive, social media), built by and for AAVE speakers to reduce dialect bias in NLP models. Her most-starred repository (23★).",
      "excerpt": {
        "type": "quote",
        "text": "When I'm saying 'What up, my brother?' I'm not being unintelligent; I'm being strategic and calling on our ancestors with that conversation.",
        "source": "Stanford HAI — Building Inclusive NLP",
        "why": "A dataset as an act of representation — closing a real gap in how language models understand dialect."
      },
      "proof": [
        {
          "label": "aave_corpora on GitHub (23★)",
          "url": "https://github.com/jazmiahenry/aave_corpora"
        },
        {
          "label": "Stanford HAI — Jazmia Henry: Building Inclusive NLP",
          "url": "https://hai.stanford.edu/news/jazmia-henry-building-inclusive-nlp"
        }
      ],
      "evidence": [
        "Built and released the AAVE Corpora — a 141k+ word open dataset of African American Vernacular English (Stanford HAI) to reduce dialect bias in NLP."
      ],
      "start": 2022
    },
    {
      "id": "book-bias",
      "kind": "book",
      "kindLabel": "Book chapter · McGraw-Hill",
      "label": "Combatting Bias in Large Language Models",
      "level": "Advanced",
      "year": null,
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "NLP",
        "Embeddings & Retrieval"
      ],
      "tags": [
        "book",
        "bias",
        "llm",
        "word-embeddings",
        "responsible-ai",
        "mcgraw-hill",
        "published-author"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Book chapter for McGraw-Hill on combatting bias in large language models, with a companion notebook teaching how word embeddings are created, visualized and probed for bias.",
      "excerpt": null,
      "proof": [
        {
          "label": "Companion code — fun-with-word-embs on GitHub",
          "url": "https://github.com/jazmiahenry/fun-with-word-embs"
        },
        {
          "label": "University of Oxford (OII) profile",
          "url": "https://www.oii.ox.ac.uk/people/profiles/jazmia-henry/"
        }
      ],
      "evidence": [
        "Published author: wrote the McGraw-Hill book chapter \"Combatting Bias in Large Language Models\" with a companion word-embeddings tutorial."
      ],
      "start": null
    },
    {
      "id": "book-alignment",
      "kind": "book",
      "kindLabel": "Book chapter · Bloomsbury Academic",
      "label": "AI Alignment and Ethics",
      "level": "Advanced",
      "year": null,
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "Evaluation"
      ],
      "tags": [
        "book",
        "alignment",
        "ethics",
        "bloomsbury",
        "responsible-ai",
        "published-author"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Contributing author on AI alignment and ethics for Bloomsbury Academic.",
      "excerpt": null,
      "proof": [
        {
          "label": "University of Oxford (OII) profile",
          "url": "https://www.oii.ox.ac.uk/people/profiles/jazmia-henry/"
        }
      ],
      "evidence": [
        "Contributing author on \"AI Alignment and Ethics\" (Bloomsbury Academic)."
      ],
      "start": null
    },
    {
      "id": "talk-sds",
      "kind": "talk",
      "kindLabel": "Podcast · Super Data Science",
      "label": "End-to-End Foundation Models for Energy",
      "level": "Advanced",
      "year": "2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "LLMs / Foundation Models",
        "Reinforcement Learning",
        "Systems / Distributed Training"
      ],
      "tags": [
        "talk",
        "podcast",
        "foundation-models",
        "energy",
        "reinforcement-learning",
        "reward-hacking",
        "tokenizer",
        "jon-krohn"
      ],
      "tech_stack": [],
      "rl_techniques": [
        "RL",
        "reward modeling"
      ],
      "summary": "In conversation with Jon Krohn (Super Data Science ep. 995): what it takes to build end-to-end foundation models for energy — turning decades of handwritten oil-and-gas documents into training data, bespoke tokenizers, RL, and inference at scale. Explains why RL training is 'bursty' on the GPU, what reward hacking is, and how her grounded continuous-evaluation framework fixes it.",
      "excerpt": {
        "type": "quote",
        "text": "Reinforcement learning models are bursty: they idle the GPU during reward calculation, then dump enormous load on it all at once.",
        "source": "Super Data Science ep. 995 · May 2026",
        "why": "A systems-level insight into RL training economics that most practitioners miss."
      },
      "proof": [
        {
          "label": "Super Data Science ep. 995",
          "url": "https://www.superdatascience.com/995"
        },
        {
          "label": "Watch on YouTube",
          "url": "https://www.youtube.com/watch?v=zNIb2jEmGG8"
        }
      ],
      "evidence": [
        "Featured guest on Super Data Science (ep. 995) with Jon Krohn on end-to-end foundation models for the energy industry."
      ],
      "start": 2026
    },
    {
      "id": "talk-neurips",
      "kind": "talk",
      "kindLabel": "Keynote & Area Chair · NeurIPS 2022",
      "label": "Operationalizing Bias Reduction",
      "level": "Advanced",
      "year": "2022",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "Evaluation"
      ],
      "tags": [
        "keynote",
        "neurips",
        "area-chair",
        "bias-reduction",
        "global-south-in-ai",
        "conversational-agents"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Keynote speaker and area chair at the NeurIPS 2022 Global South in AI affinity event — on keeping AI a 'learning AI' by operationalizing bias reduction post-production in chatbots and conversational agents.",
      "excerpt": {
        "type": "quote",
        "text": "Keeping AI a learning AI: how to operationalize bias reduction post-production in chatbots and conversational agents.",
        "source": "NeurIPS 2022 · Global South in AI",
        "why": "Bias reduction as an operational, in-production discipline — not a one-time pre-deployment check."
      },
      "proof": [
        {
          "label": "NeurIPS 2022 event",
          "url": "https://nips.cc/virtual/2022/66184"
        }
      ],
      "evidence": [
        "Keynote speaker and area chair at NeurIPS 2022 (Global South in AI); also served six reviews on the Evaluations & Datasets track."
      ],
      "start": 2022
    },
    {
      "id": "talk-conf",
      "kind": "talk",
      "kindLabel": "Conference speaker",
      "label": "PyTorch Conference & WiDS 2024",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Systems / Distributed Training",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "talk",
        "pytorch",
        "wids",
        "simulation-systems",
        "scaling-inequality",
        "speaker"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Speaker at the PyTorch Conference 2024 (AI Simulation Systems) and Women in Data Science 2024 (Scaling Inequality in LLMs).",
      "excerpt": null,
      "proof": [
        {
          "label": "PyTorch Conference 2024 speakers",
          "url": "https://pytorch2024.sched.com/directory/speakers"
        }
      ],
      "evidence": [
        "Invited speaker at the PyTorch Conference 2024 (AI Simulation Systems) and WiDS 2024 (Scaling Inequality in LLMs)."
      ],
      "start": 2024
    },
    {
      "id": "talk-sdo",
      "kind": "talk",
      "kindLabel": "Interview · Scaling DataOps",
      "label": "Data Challenges Faced by AI Researchers",
      "level": "Intermediate",
      "year": "2023",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Reinforcement Learning",
        "Data & Datasets"
      ],
      "tags": [
        "interview",
        "reinforcement-learning",
        "simulation",
        "dataops",
        "leadership"
      ],
      "tech_stack": [],
      "rl_techniques": [
        "RL"
      ],
      "summary": "Guest interview (Scaling DataOps, interviewed by Mark Freeman) on the unexpected data challenges of AI research and leading IC teams.",
      "excerpt": {
        "type": "quote",
        "text": "In reinforcement learning, you are training an agent to understand a physical space using a simulated environment. If you want your IC to thrive, you have to trust your team.",
        "source": "Scaling DataOps · 2023",
        "why": "Connects the technical (RL-in-simulation) with the human (trusting individual contributors)."
      },
      "proof": [
        {
          "label": "SDO 015 — Scaling DataOps",
          "url": "https://scalingdataops.substack.com/p/sdo-015-the-unexpected-data-challenges"
        }
      ],
      "evidence": [
        "Interviewed on Scaling DataOps about RL-in-simulation and leading individual contributors."
      ],
      "start": 2023
    },
    {
      "id": "art-roi",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "The Enterprise AI Learning Crisis",
      "level": "Intermediate",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "LLMs / Foundation Models",
        "Evaluation"
      ],
      "tags": [
        "enterprise-ai",
        "roi",
        "agents",
        "curriculum-learning",
        "training-methodology"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Argues enterprise AI's ROI problem is a learning-methodology failure, not a technology limitation, and proposes a four-stage curriculum for training agentic systems.",
      "excerpt": {
        "type": "quote",
        "text": "Companies are trying to train AI like they train software, when they should be training it like they train humans.",
        "source": "Medium · 2025-06-30",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://ai.gopubby.com/the-enterprise-ai-learning-crisis-why-97-cant-measure-roi-b372cfe01eeb"
        }
      ],
      "evidence": [
        "Wrote \"The Enterprise AI Learning Crisis\" (Medium, 2025)."
      ],
      "start": 2025
    },
    {
      "id": "art-liabilities",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "Converting AI Liabilities into Strategic Assets",
      "level": "Intermediate",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "Multi-Agent Systems"
      ],
      "tags": [
        "alignment",
        "value-sensitive-design",
        "agents",
        "finance",
        "safety"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "A tripartite value-sensitive design framework (conceptual, empirical, technical) for aligning agents to human values, via a financial-advisory failure scenario.",
      "excerpt": {
        "type": "quote",
        "text": "Alignment isn't about making AI systems more accurate or faster. It's about ensuring AI agents understand and serve human values.",
        "source": "Medium · 2025-06-23",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://medium.com/@jazmia.henry/from-dangerous-to-valuable-converting-ai-liabilities-into-strategic-assets-0c9333937d23"
        }
      ],
      "evidence": [
        "Wrote \"Converting AI Liabilities into Strategic Assets\" (Medium, 2025)."
      ],
      "start": 2025
    },
    {
      "id": "art-actionspace",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "The $11 Billion Problem: Your Agent's Action Space",
      "level": "Intermediate",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Multi-Agent Systems",
        "Reinforcement Learning"
      ],
      "tags": [
        "agents",
        "action-space",
        "roi",
        "curriculum-learning",
        "alignment-constraints"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Identifies the core agent flaw — strong state understanding paired with chaotic action selection — and prescribes static scoring, constrained dynamic learning, and curriculum learning.",
      "excerpt": {
        "type": "quote",
        "text": "42% of companies abandoned most of their AI initiatives in 2025, up from just 17% in 2024.",
        "source": "Medium · 2025-06-12",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://medium.com/data-science-collective/the-11-billion-problem-why-your-ai-agents-action-space-is-killing-your-roi-67b0d4609ec6"
        }
      ],
      "evidence": [
        "Wrote \"The $11 Billion Problem: Your Agent's Action Space\" (Medium, 2025)."
      ],
      "start": 2025
    },
    {
      "id": "art-broken",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "Your AI Agent Isn't Broken, It's Poorly Designed",
      "level": "Intermediate",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Multi-Agent Systems",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "agents",
        "value-sensitive-design",
        "friedman",
        "design-methodology",
        "microsoft"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Advocates systematic value-sensitive design before coding, using Friedman's tripartite method and real user-workflow understanding.",
      "excerpt": {
        "type": "quote",
        "text": "Systems built like this are brittle and are likely to fail.",
        "source": "Medium · 2025-06-09",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://medium.com/@jazmia.henry/your-ai-agent-isn-t-broken-it-s-poorly-designed-19f296392484"
        }
      ],
      "evidence": [
        "Wrote \"Your AI Agent Isn't Broken, It's Poorly Designed\" (Medium, 2025)."
      ],
      "start": 2025
    },
    {
      "id": "art-blackbox",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "Unveiling the Black Box: Explainability Through Simulation",
      "level": "Intermediate",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Simulation",
        "Evaluation"
      ],
      "tags": [
        "explainability",
        "simulation",
        "counterfactuals",
        "regulated-industries",
        "transparency"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Uses simulated environments for AI transparency — controlled experimentation, attention visualization and counterfactual explanations for regulated industries.",
      "excerpt": {
        "type": "quote",
        "text": "Simulations overcome the black box problem affecting deep learning adoption in regulated industries.",
        "source": "Medium · 2024-09-03",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://medium.com/@jazmia.henry/unveiling-the-black-box-ai-explainability-through-simulation-dfb3fb277c07"
        }
      ],
      "evidence": [
        "Wrote \"Unveiling the Black Box: Explainability Through Simulation\" (Medium, 2024)."
      ],
      "start": 2024
    },
    {
      "id": "art-isozero",
      "kind": "article",
      "kindLabel": "Article · Medium",
      "label": "Iso AI: Goodbye Prompting and RAGs",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Simulation",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "simulation",
        "zero-shot",
        "reasoning",
        "isozero",
        "svamp"
      ],
      "tech_stack": [],
      "rl_techniques": [],
      "summary": "Introduces IsoZero — zero-shot multi-step reasoning via simulation, without prompt engineering or RAG.",
      "excerpt": {
        "type": "quote",
        "text": "IsoZero achieves 87% accuracy on the SVAMP test set.",
        "source": "Medium · 2024-08-26",
        "why": "A distilled thesis from her writing on agent design and alignment."
      },
      "proof": [
        {
          "label": "Read on Medium",
          "url": "https://medium.com/@jazmia.henry/iso-ai-goodbye-prompting-and-rags-hello-simulation-environments-105dcd168c33"
        }
      ],
      "evidence": [
        "Wrote \"Iso AI: Goodbye Prompting and RAGs\" (Medium, 2024)."
      ],
      "start": 2024
    },
    {
      "id": "cognition-engine",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Cognition Engine",
      "level": "Expert",
      "year": "2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Reinforcement Learning",
        "Multi-Agent Systems",
        "Simulation"
      ],
      "tags": [
        "mcts",
        "uct",
        "arc-agi",
        "planning",
        "world-model",
        "metacognition",
        "core-knowledge",
        "search",
        "from-scratch",
        "agents"
      ],
      "tech_stack": [
        "numpy",
        "pillow",
        "pydantic",
        "arc-agi",
        "arcengine"
      ],
      "rl_techniques": [
        "MCTS/UCT",
        "Monte Carlo Tree Search",
        "Simulation Ensemble"
      ],
      "summary": "A pure-algorithmic (no neural nets, no LLMs) agent for the ARC-AGI-3 competition built as a four-stage cognitive cascade: connected-component perception, symbolic rule-induction world model, UCT-based MCTS planning with hierarchical priors and a simulation ensemble, and a metacognition layer that switches strategies when the world model loses traction. It is a sophisticated, from-scratch systems-and-search implementation grounded in Spelke's Core Knowledge framework.",
      "excerpt": {
        "type": "code",
        "text": "def uct(self, c: float) -> float:\n    \"\"\"UCT selection score.\n\n    Args:\n        c: Exploration constant (sqrt(2) ~= 1.41 is standard).\n\n    Returns:\n        Score; +inf for unvisited nodes to guarantee exploration.\n    \"\"\"\n    if self.visits == 0 or self.parent is None or self.parent.visits == 0:\n        return float('inf')\n    return self.q_value + c * math.sqrt(\n        math.log(self.parent.visits) / self.visits\n    )",
        "source": "cognitive/planning/mcts.py",
        "why": "Textbook-clean UCB1/UCT selection with correct unvisited-node handling, at the core of a hand-rolled MCTS planner that uses lightweight hashable states so thousands of simulations fit inside the API round-trip budget."
      },
      "proof": [
        {
          "label": "cognition-engine on GitHub",
          "url": "https://github.com/jazmiahenry/cognition-engine"
        }
      ],
      "evidence": [
        "Built the Cognition Engine for ARC-AGI-3: a pure-algorithmic four-stage cognitive cascade (perception → world model → UCT-MCTS planning → metacognition) with a hand-rolled MCTS planner."
      ],
      "start": 2026
    },
    {
      "id": "atari_gail",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Atari GAIL + Sharpened Cosine Similarity",
      "level": "Expert",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Reinforcement Learning",
        "Computer Vision"
      ],
      "tags": [
        "gail",
        "imitation-learning",
        "inverse-rl",
        "sharpened-cosine-similarity",
        "atari",
        "policy-value",
        "novel-research"
      ],
      "tech_stack": [
        "PyTorch",
        "Keras",
        "OpenAI Gym / Atari"
      ],
      "rl_techniques": [
        "GAIL",
        "Inverse Reinforcement Learning",
        "Policy/Value (AlphaGo-style)"
      ],
      "summary": "Solves an Atari control task with Generative Adversarial Imitation Learning, replacing standard convolutional feature extraction with Sharpened Cosine Similarity layers for lower-noise feature detection. Combines an AlphaGo-style policy/value approach with a GAN-like discriminator, blending inverse RL cost extraction with RL policy learning; a genuinely novel research combination with 8 stars.",
      "excerpt": {
        "type": "code",
        "text": "def forward(self, inputs):\n    # Reshape the input tensor\n    x = inputs.view(-1, self.flat_size, self.channels * self.kernel_size ** 2)\n\n    # Normalize the input and weight tensors\n    x_norm = self.l2_normal(x, axis=2)\n    w_norm = self.l2_normal(self.w, axis=1)\n\n    # Compute cosine similarity\n    x = torch.matmul(x / x_norm, self.w / w_norm)\n\n    # Apply sharpening function\n    sign = torch.sign(x)\n    x = torch.abs(x) + 1e-12\n    x = torch.pow(x + self.b ** 2, torch.sigmoid(self.p) * F.softplus(self.p))\n    x = sign * x\n    x = x.view(-1, self.output_y, self.output_x, self.units)\n    return x",
        "source": "src/prod/SharpCosSim2D.py",
        "why": "A from-scratch PyTorch Sharpened Cosine Similarity layer: L2-normalizes signal and kernel to compute true cosine similarity, then applies a learnable sign-preserving sharpening exponent, a subtle numerically-careful reimplementation of a non-standard conv alternative."
      },
      "proof": [
        {
          "label": "atari_gail on GitHub",
          "url": "https://github.com/jazmiahenry/atari_gail"
        }
      ],
      "evidence": [
        "Combined Generative Adversarial Imitation Learning with a from-scratch Sharpened Cosine Similarity layer replacing convolutions — original RL research (8★)."
      ],
      "start": 2024
    },
    {
      "id": "math-multi-agent",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Math Multi-Agent · Virtual Tools",
      "level": "Advanced",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Multi-Agent Systems",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "multi-agent",
        "tool-learning",
        "skill-compilation",
        "llm-agents",
        "finance",
        "reusable-tools"
      ],
      "tech_stack": [
        "Python",
        "TypeScript",
        "Node.js",
        "OpenAI/LLM"
      ],
      "rl_techniques": [],
      "summary": "A natural-language financial-analysis system pairing a Python agent layer with a TypeScript math-tools server, where an LLM reasons about and explains tool selection. Its standout idea is a Virtual Tool Manager that learns successful tool-call sequences and bundles them into reusable 'virtual tools', a form of experiential skill compilation for agents.",
      "excerpt": {
        "type": "code",
        "text": "class VirtualTool:\n    \"\"\"Represents a learned sequence of tool calls bundled as a single operation.\n\n    A VirtualTool encapsulates a sequence of mathematical operations that has\n    been proven to reliably solve a specific class of problems. It includes\n    metadata about the problem pattern it solves and performance metrics.\n    \"\"\"\n\n    def __init__(self, name, description, tool_sequence, problem_pattern,\n                 confidence=0.0, execution_count=0, success_rate=0.0,\n                 created_at=None):\n        ...\n\n    def find_matching_tool(self, problem_description, params):\n        \"\"\"Retrieve a learned tool whose problem_pattern matches the query.\"\"\"",
        "source": "python_agent/src/tools/virtual_tool_manager.py",
        "why": "Clean abstraction for agent skill reuse: successful multi-step tool sequences are promoted into first-class 'virtual tools' with confidence and success-rate tracking and pattern-matched retrieval, a lightweight learned-skill library for LLM agents."
      },
      "proof": [
        {
          "label": "math-multi-agent on GitHub",
          "url": "https://github.com/jazmiahenry/math-multi-agent"
        }
      ],
      "evidence": [
        "Built a multi-agent financial-analysis system with a Virtual Tool Manager that compiles successful tool-call sequences into reusable learned skills."
      ],
      "start": 2025
    },
    {
      "id": "iso-fin",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Iso Financial Tool",
      "level": "Advanced",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Simulation",
        "LLMs / Foundation Models",
        "Multi-Agent Systems"
      ],
      "tags": [
        "monte-carlo",
        "cvar",
        "risk-parity",
        "quant-finance",
        "tail-risk",
        "bayesian",
        "simulation"
      ],
      "tech_stack": [
        "numpy",
        "pandas",
        "cvxpy",
        "Streamlit",
        "Polygon.io",
        "OpenAI GPT"
      ],
      "rl_techniques": [],
      "summary": "A financial portfolio analysis MVP combining Monte Carlo simulation, scenario analysis, Risk Parity optimization, Conditional Value-at-Risk (CVaR) tail-risk analysis, and Bayesian scenario ranking, fronted by a GPT-based financial educator and a Streamlit dashboard. Shows solid quantitative-finance and simulation engineering across a clean modular package.",
      "excerpt": {
        "type": "code",
        "text": "final_values = simulation_paths[:, -1]\nreturns = (final_values - initial_investment) / initial_investment\nlosses = -returns\n\n# Value at Risk at the specified confidence level\nvar = np.percentile(losses, self.confidence_level * 100)\n\n# CVaR: expected loss in the tail beyond VaR\ncvar = np.mean(losses[losses >= var])",
        "source": "iso_financial_mvp/simulation_engines/cvar.py",
        "why": "Correct, vectorized CVaR implementation over Monte Carlo paths: computes VaR as a loss percentile then averages only the tail losses beyond it, the textbook definition of expected shortfall done cleanly in numpy."
      },
      "proof": [
        {
          "label": "iso-fin on GitHub",
          "url": "https://github.com/jazmiahenry/iso-fin"
        }
      ],
      "evidence": [
        "Built Iso-Fin: Monte Carlo simulation, CVaR tail-risk, risk-parity optimization and Bayesian scenario ranking behind a Streamlit dashboard."
      ],
      "start": 2025
    },
    {
      "id": "ethical_allocation_agent",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Ethical Allocation Agent",
      "level": "Advanced",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Multi-Agent Systems",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "fairness",
        "rawlsian",
        "maximin",
        "veil-of-ignorance",
        "multi-agent",
        "moral-philosophy",
        "gini",
        "welfare"
      ],
      "tech_stack": [
        "Python",
        "numpy",
        "OpenAI",
        "asyncio"
      ],
      "rl_techniques": [],
      "summary": "Reference implementation for a research paper comparing philosophical frameworks (individual fairness, social/utilitarian, and Rawlsian veil-of-ignorance/maximin) as distinct LLM allocation agents, evaluated across static, dynamic, and cultural scenarios with equity, welfare, and Gini metrics. A rigorous multi-agent fairness study operationalizing moral philosophy in code.",
      "excerpt": {
        "type": "code",
        "text": "def maximin_decision(options, outcomes):\n    \"\"\"Implements the maximin decision principle\"\"\"\n    if not options or not outcomes or len(options) != len(outcomes):\n        raise ValueError(\"options and outcomes must be non-empty and same length\")\n\n    worst_outcomes = [min(scenario) for scenario in outcomes]\n    best_index = np.argmax(worst_outcomes)\n    return options[best_index], worst_outcomes[best_index]",
        "source": "src/fairness_mas/agents/veil_allocator.py",
        "why": "Directly encodes Rawls' veil-of-ignorance maximin rule (maximize the worst-case outcome) as the decision core of an anonymous fairness agent, a crisp translation of a philosophical principle into a decision function."
      },
      "proof": [
        {
          "label": "ethical_allocation_agent on GitHub",
          "url": "https://github.com/jazmiahenry/ethical_allocation_agent"
        }
      ],
      "evidence": [
        "Operationalized moral philosophy in code — Rawlsian maximin, utilitarian and individual-fairness allocators as distinct LLM agents, evaluated on equity/welfare/Gini."
      ],
      "start": 2025
    },
    {
      "id": "car_simulator",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Car Simulator (RL)",
      "level": "Advanced",
      "year": "2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Reinforcement Learning",
        "Simulation"
      ],
      "tags": [
        "reinforcement-learning",
        "gymnasium",
        "stable-baselines3",
        "continuous-control",
        "self-driving",
        "simulation"
      ],
      "tech_stack": [
        "Gymnasium",
        "Stable-Baselines3",
        "PyTorch",
        "Pygame"
      ],
      "rl_techniques": [
        "Stable-Baselines3 policy learning (continuous control)"
      ],
      "summary": "A custom Gymnasium RL environment for multi-car driving with continuous action spaces and dynamic conditions (time of day, weather-driven friction, weekday/weekend), trained via Stable-Baselines3 and visualized with Pygame. A clean, well-typed simulation-plus-training package.",
      "excerpt": {
        "type": "code",
        "text": "class CarRLEnvironment(gym.Env):\n    def __init__(self, num_cars=1, time_of_day=\"12:00\", is_rainy=False, is_weekday=True):\n        super().__init__()\n        self.num_cars = num_cars\n        self.time_of_day = self.convert_time(time_of_day)\n        self.friction = 0.4 if is_rainy else 0.8\n\n        self.action_space = spaces.Box(low=-1, high=1, shape=(num_cars * 2,), dtype=np.float32)\n        # [x, y, vx, vy, angle] per car + [time_of_day, is_rainy, is_weekday]\n        self.observation_space = spaces.Box(\n            low=-np.inf, high=np.inf, shape=(num_cars * 5 + 3,), dtype=np.float32\n        )",
        "source": "CarSimulator/car_rl_environment.py",
        "why": "A properly specified Gymnasium environment: continuous Box action/observation spaces sized dynamically to the number of cars, with environmental context (weather changing friction) folded into the observation, showing correct RL environment design."
      },
      "proof": [
        {
          "label": "car_simulator on GitHub",
          "url": "https://github.com/jazmiahenry/car_simulator"
        }
      ],
      "evidence": [
        "Built a custom Gymnasium RL environment for multi-car continuous control with weather/time context, trained via Stable-Baselines3."
      ],
      "start": 2026
    },
    {
      "id": "document_sorter",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Document Sorter",
      "level": "Intermediate",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "NLP",
        "Embeddings & Retrieval"
      ],
      "tags": [
        "nlp",
        "clustering",
        "kmeans",
        "elbow-method",
        "pip-package",
        "shipped",
        "retrieval"
      ],
      "tech_stack": [
        "scikit-learn",
        "KMeans",
        "Python (pip package)"
      ],
      "rl_techniques": [],
      "summary": "A pip-installable CLI utility that extracts text from many file types (PDF, DOCX, XLSX, CSV, TXT, MD, TEX), clusters documents by content similarity with automatic k selection via the elbow method, and sorts them into keyword-named folders. A clean, shipped, real-world NLP tool.",
      "excerpt": {
        "type": "code",
        "text": "def elbow_method(distance_matrix: np.ndarray, max_clusters: int = 10) -> int:\n    \"\"\"Determine the optimal number of clusters using the elbow method.\"\"\"\n    max_clusters = min(max_clusters, n_samples - 1)\n    wcss = []\n    for i in range(1, max_clusters + 1):\n        kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300,\n                        n_init=10, random_state=0)\n        kmeans.fit(distance_matrix)\n        wcss.append(kmeans.inertia_)\n    elbow_point = np.argmin(differences) + 1\n    return min(elbow_point + 1, n_samples)",
        "source": "document_sorter/main.py",
        "why": "Automatic cluster-count selection via the elbow method with sensible guards against degenerate small-sample cases, letting the tool sort documents with zero user tuning."
      },
      "proof": [
        {
          "label": "document_sorter on GitHub",
          "url": "https://github.com/jazmiahenry/document_sorter"
        }
      ],
      "evidence": [
        "Shipped document-sorter, a pip-installable tool that clusters mixed documents by content with automatic elbow-method k-selection."
      ],
      "start": 2024
    },
    {
      "id": "rlhf-course",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "RLHF Course",
      "level": "Advanced",
      "year": "2026",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Reinforcement Learning",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "rlhf",
        "alignment",
        "reward-modeling",
        "curriculum",
        "teaching",
        "course"
      ],
      "tech_stack": [
        "Jupyter",
        "Python"
      ],
      "rl_techniques": [
        "RLHF",
        "Reward Modeling",
        "Mathematical Alignment"
      ],
      "summary": "A structured, multi-module course on RLHF and RL-based alignment, spanning mathematical foundations, trajectory/curriculum design, two-stage AI integration, and simulation experiments (including a financial-agent alignment case study). Demonstrates deep teaching-level command of RLHF theory and practice.",
      "excerpt": null,
      "proof": [
        {
          "label": "rlhf-course on GitHub",
          "url": "https://github.com/jazmiahenry/rlhf-course"
        }
      ],
      "evidence": [
        "Authored a multi-module RLHF course spanning mathematical foundations, trajectory/curriculum design and alignment case studies."
      ],
      "start": 2026
    },
    {
      "id": "prompting_fairness",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Prompting Fairness (code)",
      "level": "Advanced",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Evaluation",
        "AI Fairness & Ethics",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "fairness",
        "dictator-game",
        "behavioral-economics",
        "llm-evaluation",
        "framing",
        "persona"
      ],
      "tech_stack": [
        "Python",
        "Jupyter",
        "Jinja2",
        "OpenAI"
      ],
      "rl_techniques": [],
      "summary": "Companion code for the paper 'Prompting Fairness: Artificial Intelligence as Game Players', running 101+ rounds of the economic dictator game against an LLM to probe fairness, trust-conditioning, framing effects, persona effects, and inequality aversion. A well-designed behavioral-economics evaluation of LLM decision-making.",
      "excerpt": null,
      "proof": [
        {
          "label": "prompting_fairness on GitHub",
          "url": "https://github.com/jazmiahenry/prompting_fairness"
        }
      ],
      "evidence": [
        "Ran 101+ rounds of the economic dictator game against an LLM to probe fairness, trust-conditioning, framing and persona effects."
      ],
      "start": 2025
    },
    {
      "id": "public_logic_prompts",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Public Logic Prompts",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "LLMs / Foundation Models",
        "Evaluation",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "reasoning",
        "symbolic-logic",
        "red-team",
        "self-reasoning",
        "llm-evaluation",
        "harm-taxonomy"
      ],
      "tech_stack": [
        "Jupyter",
        "Python",
        "Anthropic red-team data"
      ],
      "rl_techniques": [],
      "summary": "Notebook-based exploration of LLM self-reasoning under ambiguity: taxonomizing harms on Anthropic red-teamed conversations, symbolic-logic argument decomposition, and testing whether socio-political identity framing or zero-sum game play shifts model reasoning. Early public research feeding the chain-of-logic line of work.",
      "excerpt": null,
      "proof": [
        {
          "label": "public_logic_prompts on GitHub",
          "url": "https://github.com/jazmiahenry/public_logic_prompts"
        }
      ],
      "evidence": [
        "Explored whether LLMs can self-reason under ambiguity — harm taxonomies on red-teamed conversations and symbolic-logic argument decomposition."
      ],
      "start": 2024
    },
    {
      "id": "responsible-ai",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Responsible AI Explainability",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "AI Fairness & Ethics",
        "LLMs / Foundation Models",
        "Evaluation"
      ],
      "tags": [
        "explainability",
        "shap",
        "dice",
        "counterfactuals",
        "model-cards",
        "responsible-ai",
        "heatmaps"
      ],
      "tech_stack": [
        "Jupyter",
        "SHAP",
        "DiCE",
        "Model Card Toolkit"
      ],
      "rl_techniques": [],
      "summary": "A tutorial and open-source repository on LLM explainability for Responsible AI practitioners, covering embedding heatmaps, model-parameter visualization, model cards, parity charts, and counterfactual comparisons to penetrate the model 'black box'. Positions her as a Responsible-AI educator and practitioner.",
      "excerpt": null,
      "proof": [
        {
          "label": "responsible-ai on GitHub",
          "url": "https://github.com/jazmiahenry/responsible-ai"
        }
      ],
      "evidence": [
        "Authored a Responsible-AI explainability tutorial — embedding heatmaps, model cards, parity charts and counterfactuals (SHAP, DiCE)."
      ],
      "start": 2024
    },
    {
      "id": "fun-with-word-embs",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "Fun with Word Embeddings",
      "level": "Intermediate",
      "year": "2023",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "NLP",
        "Embeddings & Retrieval",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "word-embeddings",
        "bias",
        "nlp",
        "book-companion",
        "visualization",
        "mcgraw-hill"
      ],
      "tech_stack": [
        "Jupyter",
        "word embeddings",
        "TensorFlow"
      ],
      "rl_techniques": [],
      "summary": "Instructional notebook companion to Jazmia's chapter 'Combatting Bias in Large Language Models' in the McGraw Hill book 'Bias in Machine Learning', teaching how word embeddings are created, visualized, and probed for bias. Establishes her as a published author on responsible AI.",
      "excerpt": null,
      "proof": [
        {
          "label": "fun-with-word-embs on GitHub",
          "url": "https://github.com/jazmiahenry/fun-with-word-embs"
        }
      ],
      "evidence": [
        "Companion notebook to the McGraw-Hill chapter \"Combatting Bias in LLMs\" — teaching how embeddings are built, visualized and probed for bias."
      ],
      "start": 2023
    },
    {
      "id": "nemo_riggs_training",
      "kind": "repo",
      "kindLabel": "Repository · Company IP",
      "label": "NeMo RIGGs Training",
      "level": "Expert",
      "year": "2026",
      "org": "Collide (RIGGs)",
      "is_company_ip": true,
      "topics": [
        "Systems / Distributed Training",
        "LLMs / Foundation Models",
        "Embeddings & Retrieval"
      ],
      "tags": [
        "nemo",
        "continued-pretraining",
        "multimodal-embeddings",
        "distributed-training",
        "petroleum",
        "systems"
      ],
      "tech_stack": [
        "NVIDIA NeMo",
        "Python"
      ],
      "rl_techniques": [],
      "summary": "Company IP (Collide/RIGGs): distributed training infrastructure for continued pre-training and multi-modal embedding models on proprietary petroleum-domain data. Demonstrates production-scale LLM pretraining and systems engineering. No source shown per IP policy.",
      "excerpt": null,
      "proof": [],
      "evidence": [
        "Built distributed continued-pretraining and multimodal-embedding infrastructure (NeMo) for the petroleum-domain RIGGs models."
      ],
      "start": 2026
    },
    {
      "id": "MLO-Capstone-Henry",
      "kind": "repo",
      "kindLabel": "Repository · Company IP",
      "label": "Manufacturing Line Optimization (RL)",
      "level": "Advanced",
      "year": "2023",
      "org": "Microsoft (Bonsai)",
      "is_company_ip": true,
      "topics": [
        "Reinforcement Learning",
        "Simulation"
      ],
      "tags": [
        "reinforcement-learning",
        "bonsai",
        "manufacturing",
        "industrial-rl",
        "throughput",
        "simulation"
      ],
      "tech_stack": [
        "Microsoft Bonsai",
        "Python",
        "Jupyter"
      ],
      "rl_techniques": [
        "Deep RL (Bonsai brain training)"
      ],
      "summary": "Capstone project (derived from Microsoft's bonsai-ManufacturingLineOptimization) training an RL 'brain' to orchestrate machine speeds in a manufacturing line and maximize throughput under machine-downtime events, using prox-sensor state abstractions. Demonstrates applied industrial RL on a Microsoft/Bonsai platform.",
      "excerpt": null,
      "proof": [
        {
          "label": "MLO-Capstone-Henry on GitHub",
          "url": "https://github.com/jazmiahenry/MLO-Capstone-Henry"
        }
      ],
      "evidence": [
        "Trained an RL brain (Microsoft Bonsai) to orchestrate machine speeds and maximize manufacturing-line throughput under downtime events."
      ],
      "start": 2023
    },
    {
      "id": "smoothquant-main",
      "kind": "repo",
      "kindLabel": "Open-source repository",
      "label": "SmoothQuant (quantization work)",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "topics": [
        "Efficient Inference / Quantization",
        "LLMs / Foundation Models"
      ],
      "tags": [
        "quantization",
        "post-training-quantization",
        "efficient-inference",
        "int8",
        "llm-serving"
      ],
      "tech_stack": [
        "Python",
        "PyTorch"
      ],
      "rl_techniques": [],
      "summary": "Private working copy related to SmoothQuant post-training quantization for LLMs. Reflects hands-on work with efficient-inference/quantization techniques; synopsis only.",
      "excerpt": null,
      "proof": [],
      "evidence": [
        "Hands-on work with SmoothQuant post-training quantization for efficient LLM inference."
      ],
      "start": 2024
    },
    {
      "id": "deci-azure",
      "kind": "repo",
      "kindLabel": "Repository · Company IP",
      "label": "Deci + Azure ML Optimization",
      "level": "Advanced",
      "year": "2023",
      "org": "Microsoft (Azure) / Deci",
      "is_company_ip": true,
      "topics": [
        "Efficient Inference / Quantization",
        "Systems / Distributed Training"
      ],
      "tags": [
        "model-optimization",
        "azure-ml",
        "efficient-inference",
        "deci",
        "deployment"
      ],
      "tech_stack": [
        "Jupyter",
        "Azure ML",
        "Deci"
      ],
      "rl_techniques": [],
      "summary": "Private work integrating Deci model-optimization with Azure ML. Company/vendor-adjacent; synopsis only, no source shown.",
      "excerpt": null,
      "proof": [],
      "evidence": [
        "Integrated Deci model-optimization with Azure ML for efficient model deployment."
      ],
      "start": 2023
    },
    {
      "id": "tanagram",
      "kind": "repo",
      "kindLabel": "Research repository · private",
      "label": "Tanagram — Code-Review Rule Mining",
      "level": "Expert",
      "year": "2025",
      "org": null,
      "is_company_ip": false,
      "private": true,
      "topics": [
        "NLP",
        "LLMs / Foundation Models",
        "Data & Datasets"
      ],
      "tags": [
        "nlp",
        "code-review",
        "rule-induction",
        "clustering",
        "topic-modeling",
        "llm-pipeline",
        "ollama",
        "pattern-mining",
        "evaluation"
      ],
      "tech_stack": [
        "Python",
        "Ollama",
        "clustering",
        "hierarchical topic modeling"
      ],
      "rl_techniques": [],
      "summary": "An 11-step pipeline that mines enforceable code-review rules from thousands of real pull-request comments — bot filtering, train/val/test splitting, multi-algorithm clustering, hierarchical topic modeling, and LLM rule generation with real examples and frequency data.",
      "excerpt": {
        "type": "quote",
        "text": "Filters 3,612 bot comments out of 5,543, clusters the rest at a 0.951 quality score, then generates specific, frequency-backed review rules — each with real examples from the dataset.",
        "source": "Tanagram · PR Comment Analysis Pipeline",
        "why": "Turns tribal code-review knowledge into programmatically enforceable rules — an original NLP + LLM pipeline with measured quality."
      },
      "proof": [],
      "evidence": [
        "Built Tanagram, an 11-step NLP + LLM pipeline that mines enforceable code-review rules from thousands of real PR comments (0.951 clustering quality)."
      ],
      "start": 2025
    },
    {
      "id": "chain-of-logic",
      "kind": "repo",
      "kindLabel": "Research repository · private",
      "label": "Chain of Logic Prompts",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "private": true,
      "topics": [
        "Evaluation",
        "LLMs / Foundation Models",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "reasoning",
        "symbolic-logic",
        "red-team",
        "harm-taxonomy",
        "self-reasoning",
        "identity-framing",
        "llm-evaluation"
      ],
      "tech_stack": [
        "Python",
        "Jupyter",
        "Anthropic red-team data"
      ],
      "rl_techniques": [],
      "summary": "Research into how LLMs self-reason under ambiguity: using symbolic logic to decompose arguments, taxonomizing harms on Anthropic red-teamed conversations, and testing whether a model reasons differently when given a subject's socio-political identity.",
      "excerpt": {
        "type": "quote",
        "text": "Explores whether an LLM reasons differently when it breaks arguments down with symbolic logic — and whether socio-political identity framing shifts that reasoning.",
        "source": "Chain of Logic Prompts",
        "why": "Probes the failure modes of LLM reasoning under ambiguity and identity framing — the deep research behind the public logic-prompts line."
      },
      "proof": [],
      "evidence": [
        "Researched LLM self-reasoning under ambiguity — symbolic-logic argument decomposition and harm taxonomies over Anthropic red-team data, with identity-framing tests."
      ],
      "start": 2024
    },
    {
      "id": "simulate-and-evaluate",
      "kind": "repo",
      "kindLabel": "Research repository · private",
      "label": "Simulate & Evaluate",
      "level": "Advanced",
      "year": "2024",
      "org": null,
      "is_company_ip": false,
      "private": true,
      "topics": [
        "Simulation",
        "Evaluation",
        "Reinforcement Learning"
      ],
      "tags": [
        "simulation",
        "evaluation",
        "deterministic-verifier",
        "rl",
        "agent-scoring",
        "iso"
      ],
      "tech_stack": [
        "Python"
      ],
      "rl_techniques": [],
      "summary": "A private research framework for simulating agent behavior and scoring it with deterministic evaluators — the experimental substrate behind the Iso line (IsoTune and ISOPro).",
      "excerpt": null,
      "proof": [],
      "evidence": [
        "Built a private simulate-and-evaluate framework pairing agent simulation with deterministic scoring — the research substrate behind IsoTune and ISOPro."
      ],
      "start": 2024
    },
    {
      "id": "dissertation",
      "kind": "paper",
      "kindLabel": "Doctoral research · University of Oxford",
      "label": "DPhil Dissertation Research",
      "level": "Expert",
      "year": "2024 – present",
      "org": null,
      "is_company_ip": false,
      "private": true,
      "topics": [
        "Evaluation",
        "LLMs / Foundation Models",
        "AI Fairness & Ethics"
      ],
      "tags": [
        "dissertation",
        "dphil",
        "oxford",
        "evaluation",
        "ethics",
        "doctoral-research"
      ],
      "tech_stack": [
        "Python",
        "Jupyter",
        "LaTeX"
      ],
      "rl_techniques": [],
      "summary": "Doctoral (DPhil) research at the University of Oxford — papers, analysis and code on the rigorous evaluation of language models and the ethics of deployed AI.",
      "excerpt": null,
      "proof": [
        {
          "label": "University of Oxford (OII) profile",
          "url": "https://www.oii.ox.ac.uk/people/profiles/jazmia-henry/"
        }
      ],
      "evidence": [
        "Conducting DPhil research at the University of Oxford on rigorous LLM evaluation and the ethics of deployed AI."
      ],
      "start": 2024
    },
    {
      "id": "plato-azure",
      "kind": "repo",
      "kindLabel": "Repository · Microsoft Azure",
      "label": "Plato — RL on Azure ML",
      "level": "Expert",
      "year": "2022 – 2024",
      "org": "Microsoft (Azure)",
      "is_company_ip": true,
      "private": false,
      "topics": [
        "Systems / Distributed Training",
        "Reinforcement Learning",
        "Simulation"
      ],
      "tags": [
        "azure-ml",
        "ray",
        "rllib",
        "distributed-rl",
        "domain-randomization",
        "ray-tune",
        "mlflow",
        "docker",
        "scale-out"
      ],
      "tech_stack": [
        "Azure ML",
        "Ray RLlib",
        "Ray Tune",
        "MLflow",
        "Docker",
        "Gymnasium"
      ],
      "rl_techniques": [
        "distributed RL"
      ],
      "summary": "A Python toolkit for training reinforcement-learning agents at scale on Azure ML compute clusters via Ray RLlib — with domain randomization, hyperparameter tuning through Ray Tune, MLflow experiment tracking, and Dockerized deployment of trained agents.",
      "excerpt": {
        "type": "quote",
        "text": "Plato trains RL agents at scale on Azure ML compute via Ray RLlib — with domain randomization, Ray Tune hyperparameter search, MLflow tracking, and Dockerized deployment of trained agents.",
        "source": "Plato Toolkit · Azure ML",
        "why": "The distributed RL training platform behind production Bonsai agents — scale-out reinforcement learning as a reusable system."
      },
      "proof": [
        {
          "label": "Azure/plato on GitHub",
          "url": "https://github.com/Azure/plato"
        }
      ],
      "evidence": [
        "Co-developed Plato, a Python toolkit for scaling RL training on Azure ML via Ray RLlib — domain randomization, Ray Tune, MLflow and Dockerized agent deployment."
      ],
      "start": 2022
    },
    {
      "id": "collide-ogllm",
      "kind": "repo",
      "kindLabel": "Repository · Company IP",
      "label": "O&G Collide LLM — Fine-tuning Corpus",
      "level": "Advanced",
      "year": "2025",
      "org": "Collide",
      "is_company_ip": true,
      "private": true,
      "topics": [
        "LLMs / Foundation Models",
        "Embeddings & Retrieval",
        "Data & Datasets"
      ],
      "tags": [
        "fine-tuning",
        "oil-gas",
        "azure-ml",
        "bge-embeddings",
        "qdrant",
        "data-pipeline",
        "pdf-extraction",
        "corpus"
      ],
      "tech_stack": [
        "Azure ML",
        "BGE embeddings",
        "Qdrant",
        "Python"
      ],
      "rl_techniques": [],
      "summary": "An oil-and-gas LLM fine-tuning pipeline: a three-pass extraction process over PDFs in Azure Blob Storage, BGE embeddings stored in Qdrant for relevance search, assembling a high-quality domain training corpus.",
      "excerpt": {
        "type": "quote",
        "text": "A three-pass extraction pipeline over PDFs in Azure Blob Storage — parallel first-page extraction, BGE embeddings in Qdrant for relevance search, then targeted deep extraction — to build a high-quality oil-and-gas training corpus.",
        "source": "O&G Collide LLM · data pipeline",
        "why": "The production data-engineering that feeds domain LLM fine-tuning — the corpus discipline behind RIGGs."
      },
      "proof": [],
      "evidence": [
        "Built the O&G Collide LLM fine-tuning corpus pipeline — three-pass PDF extraction on Azure ML with BGE embeddings in Qdrant for relevance search."
      ],
      "start": 2025
    }
  ]
};
